### PR TITLE
Add nettle-aes benchmark.

### PR DESCRIPTION
**Pull request by gmarkall**
This adds an implementation of AES-256 from Nettle. It self-verifies by comparing the ciphertext to a reference copy of the expected ciphertext, and by comparing the decrypted ciphertext to the original plaintext.

ChangeLog:

        * configure: Regenerate.
        * configure.ac: Configure nettle-aes.
        * src/Makefile.am: Add nettle-aes.
        * src/Makefile.in: Regenerate.
        * src/nettle-aes/.gitignore: New file.
        * src/nettle-aes/Makefile.am: New file.
        * src/nettle-aes/Makefile.in: New file.
        * src/nettle-aes/nettle-aes.c: New file.

### CODE REVIEW

**Comment by jeremybennett** [comment]
Looks good to me. Have you managed to get it to work with Verilator?

**Comment by gmarkall** [comment]
It runs but it doesn't finish running within one hour. I might leave it going overnight to see what happens.

**Comment by LubomirBogdanov** [comment]
Hi, I can verify that the nettle-aes works on the Taiyo Yuden EYSGJN board. It takes about ~50 sec to finish.

**Comment by gmarkall** [comment]
Thanks for the review @LubomirBogdanov !

**Pull request merged**
